name: Deploy to HF Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://huggingface.co/spaces/FerdinandC777/rag-api
          git pull https://FerdinandC777:$HF_TOKEN@huggingface.co/spaces/FerdinandC777/rag-api main --rebase
          git push https://FerdinandC777:$HF_TOKEN@huggingface.co/spaces/FerdinandC777/rag-api main